name: cmems
channels:
  - conda-forge
dependencies:
  - python
  - copernicusmarine
  - xarray
  - netcdf4
  - h5netcdf
  - cftime
  - numpy
  - pandas
  - dask
  - scipy
  - matplotlib
  - cartopy
  - tqdm
  - ipykernel